algoritmo "Exercicio_2"
// Função : Algoritmo para verificar se o número informado é par ou ímpar.
// Autor : Éwerton de Oliveira Cercal
// Data : 09/09/2023
// Seção de Declarações
var
    numero: inteiro
inicio
// Seção de Comandos
    escreval("Informe um número:")
    leia(numero)

    se ((numero % 2) = 0) entao
        escreva("O número informado é par.")
    senao
        escreva("O número informado é ímpar.")
    fimse
fimalgoritmo