algoritmo "Exercicio_15"
// Função :
// 15.  Faça um pseudocódigo com uma estrutura de repetição que mostre a seguinte sequência numérica ao usuário:
//      4   9   16  25  36  49  64  81  100 121 144
// Autor : Éwerton de Oliveira Cercal
// Data : 19/09/2023
// Seção de Declarações
var
    i: inteiro
inicio
// Seção de Comandos
    para i de 2 ate 12 faca
        escreva(i * i, " ")
    fimpara
fimalgoritmo