algoritmo "Exercicio_1"
// Função :
// 1.   Faça um pseudocódigo que mostre na tela oito vezes uma frase desmotivacional para o dia de hoje!
// Autor : Éwerton de Oliveira Cercal
// Data : 19/09/2023
// Seção de Declarações
var
    i: inteiro
inicio
// Seção de Comandos
    para i de 1 ate 8 faca
        escreval("'Não existe trabalho ruim. O ruim é ter que trabalhar' - Seu Madruga")
    fimpara
fimalgoritmo