algoritmo "Exercicio_5"
// Função : Algoritmo calcula a área de um quadrado conforme valor do lado informado pelo usuário.
// Autor : Éwerton de Oliveira Cercal
// Data : 02/09/2023
// Seção de Declarações
var
    lado: inteiro
    area: inteiro
inicio
// Seção de Comandos
    escreval("Informe o lado do quadrado: ")
    leia(lado)
    area <- lado^2
    escreva("A área do quadrado é de ", area, ".")
fimalgoritmo